blueprint:
    name: Pool Pump Scheduler (Corrected)
    description: |
        Pool pump management with three operation modes: Auto, On, Off.
        In Auto mode: calculates required run time based on volume and flow rate, accounts for manual operation.
        On mode: keeps pump always running. Off mode: keeps pump always off.
    domain: automation
    input:
        pool_pump:
            name: Pump
            description: Pool pump switch entity
            selector:
                entity:
                    domain: switch

        pool_volume:
            name: Pool Volume
            description: In the same unit as pump flow rate (l, m3, gallon)
            selector:
                number:
                    min: 1
                    max: 100000
                    unit_of_measurement: 'l/m3/gal'
                    mode: box

        pump_flow_rate:
            name: Pump Flow Rate
            description: In the same unit as volume (l/h, m3/h, gph)
            selector:
                number:
                    min: 0.1
                    max: 1000
                    unit_of_measurement: 'l/h/m3/h/gph'
                    step: 0.1
                    mode: box

        maximum_run_time:
            name: Maximum Daily Run Time
            default: 8
            selector:
                number:
                    min: 1
                    max: 24
                    step: 1
                    unit_of_measurement: 'h'
                    mode: slider

        pump_interval:
            name: Pump Interval
            description: Time between pump cycles (hours)
            default: 1
            selector:
                number:
                    min: 0.5
                    max: 12
                    step: 0.5
                    unit_of_measurement: 'h'
                    mode: slider

        pool_pump_mode:
            name: Pool Pump Mode
            description: Select operation mode (Auto/On/Off)
            selector:
                entity:
                    domain: input_select

        manual_runtime_sensor:
            name: Daily Pump Runtime Sensor
            description: History stats sensor that tracks pump daily runtime (type 'time')
            selector:
                entity:
                    domain: sensor

variables:
    var_pool_pump: !input pool_pump
    var_pool_volume: !input pool_volume
    var_pump_flow_rate: !input pump_flow_rate
    var_maximum_run_time: !input maximum_run_time
    var_pump_interval: !input pump_interval
    var_pump_mode: !input pool_pump_mode
    var_manual_runtime_sensor: !input manual_runtime_sensor
    var_manual_runtime_today: '{{ states(var_manual_runtime_sensor) | float(0) }}'
    var_pump_state_changed_since: '{{ (now().timestamp() - as_timestamp(states[var_pool_pump].last_changed)) / 3600 }}'

trigger:
    - platform: time_pattern
      minutes: '/1'

condition: []

action:
    - choose:
          - conditions:
                - condition: template
                  value_template: "{{ states(var_pump_mode) == 'On' }}"
                - condition: state
                  entity_id: !input pool_pump
                  state: 'off'
            sequence:
                - service: switch.turn_on
                  target:
                      entity_id: !input pool_pump
          - conditions:
                - condition: template
                  value_template: "{{ states(var_pump_mode) == 'Off' }}"
                - condition: state
                  entity_id: !input pool_pump
                  state: 'on'
            sequence:
                - service: switch.turn_off
                  target:
                      entity_id: !input pool_pump
                - conditions:
          - condition: template
            value_template: "{{ states(var_pump_mode) == 'Auto' }}"
          - condition: state
            entity_id: !input pool_pump
            state: 'off'
          - condition: template
            value_template: '{{ var_pump_state_changed_since > var_pump_interval }}'
          - condition: template
            value_template: '{{ var_manual_runtime_today < var_maximum_run_time }}'
            sequence:
                - service: switch.turn_on
                  target:
                      entity_id: !input pool_pump
      default: []

mode: single
