blueprint:
    name: Smart Pool Pump Controller
    description: |
        Pool pump management with three operation modes: Auto, On, Off.
        In Auto mode: calculates required run time based on volume and flow rate, accounts for manual operation.
        On mode: keeps pump always running. Off mode: keeps pump always off.
    domain: automation
    input:
        start_time:
            name: Start Time
            description: Automation start time (pump can work from this time)
            default: '09:00:00'
            selector:
                time: {}

        end_time:
            name: End Time
            description: Automation end time (pump stops working after this time)
            default: '21:00:00'
            selector:
                time: {}
        pool_pump:
            name: Pump
            description: Pool pump switch entity
            default: switch.pool_pump
            selector:
                entity:
                    domain: switch

        pool_volume:
            name: Pool Volume
            description: In the same unit as pump flow rate (l, m3, gallon)
            selector:
                number:
                    min: 1
                    max: 100000
                    unit_of_measurement: 'l/m3/gal'
                    mode: box

        pump_flow_rate:
            name: Pump Flow Rate
            description: In the same unit as volume (l/h, m3/h, gph)
            selector:
                number:
                    min: 0.1
                    max: 1000
                    unit_of_measurement: 'l/h/m3/h/gph'
                    step: 0.1
                    mode: box

        water_turnover_cycles:
            name: Water Turnover Cycles
            description: Number of complete water turnovers per day (recommended 1-3)
            default: 2
            selector:
                number:
                    min: 1
                    max: 5
                    step: 1
                    mode: slider

        maximum_run_time:
            name: Maximum Daily Run Time
            default: 8
            selector:
                number:
                    min: 1
                    max: 24
                    step: 1
                    unit_of_measurement: 'h'
                    mode: slider

        pump_interval:
            name: Pump Interval
            description: Time between pump cycles (hours)
            default: 1
            selector:
                number:
                    min: 0.5
                    max: 12
                    step: 0.5
                    unit_of_measurement: 'h'
                    mode: slider

        cycle_runtime:
            name: Cycle Runtime
            description: How long pump runs in each cycle (minutes)
            default: 120
            selector:
                number:
                    min: 5
                    max: 180
                    step: 5
                    unit_of_measurement: 'min'
                    mode: slider

        pool_pump_mode:
            name: Pool Pump Mode
            description: Select operation mode (Auto/On/Off)
            default: input_select.pool_pump_mode
            selector:
                entity:
                    domain: input_select

        manual_runtime_sensor:
            name: Daily Pump Runtime Sensor
            description: History stats sensor that tracks pump daily runtime (type 'time')
            default: sensor.daily_pump_runtime_sensor
            selector:
                entity:
                    domain: sensor



variables:
    var_pool_pump: !input pool_pump
    var_pool_volume: !input pool_volume
    var_pump_flow_rate: !input pump_flow_rate
    var_water_turnover_cycles: !input water_turnover_cycles
    var_maximum_run_time: !input maximum_run_time
    var_pump_interval: !input pump_interval
    var_cycle_runtime: !input cycle_runtime
    var_pump_mode: !input pool_pump_mode
    var_manual_runtime_sensor: !input manual_runtime_sensor
    var_start_time: !input start_time
    var_end_time: !input end_time
    var_manual_runtime_today: '{{ states(var_manual_runtime_sensor) | float(0) }}'
    var_calculated_daily_limit: '{{ (var_pool_volume / var_pump_flow_rate * var_water_turnover_cycles) }}'
    var_pump_state_changed_since: '{{ (now().timestamp() - as_timestamp(states[var_pool_pump].last_changed)) / 3600 }}'
    var_pump_running_time: '{{ (now().timestamp() - as_timestamp(states[var_pool_pump].last_changed)) / 60 if states(var_pool_pump) == "on" else 0 }}'
    var_current_time: '{{ now().strftime("%H:%M:%S") }}'
    var_time_in_range: '{% if var_start_time <= var_end_time %}{{ var_start_time <= var_current_time <= var_end_time }}{% else %}{{ var_current_time >= var_start_time or var_current_time <= var_end_time }}{% endif %}'

trigger:
    - platform: time_pattern
      minutes: '/1'
    - platform: state
      entity_id: !input pool_pump_mode

condition: []

action:
    - choose:
          # Immediate shutdown if outside working hours
          - conditions:
                - condition: template
                  value_template: "{{ not var_time_in_range }}"
                - condition: state
                  entity_id: !input pool_pump
                  state: 'on'
            sequence:
                - service: switch.turn_off
                  target:
                      entity_id: !input pool_pump
                - stop: "Pump turned off, outside working hours"
          # Immediate shutdown in "Off" mode
          - conditions:
                - condition: template
                  value_template: "{{ states(var_pump_mode) == 'Off' }}"
                - condition: state
                  entity_id: !input pool_pump
                  state: 'on'
            sequence:
                - service: switch.turn_off
                  target:
                      entity_id: !input pool_pump
                - stop: "Pump turned off, automation stopped in Off mode"
          # Stop automation in "Off" mode if pump is already off
          - conditions:
                - condition: template
                  value_template: "{{ states(var_pump_mode) == 'Off' }}"
            sequence:
                - stop: "Automation stopped in Off mode"
          # Stop automation if outside working hours
          - conditions:
                - condition: template
                  value_template: "{{ not var_time_in_range }}"
            sequence:
                - stop: "Automation stopped, outside working hours"
          # Immediate activation in "On" mode
          - conditions:
                - condition: template
                  value_template: "{{ states(var_pump_mode) == 'On' }}"
                - condition: state
                  entity_id: !input pool_pump
                  state: 'off'
            sequence:
                - service: switch.turn_on
                  target:
                      entity_id: !input pool_pump
          # Auto cycle shutdown after runtime expires
          - conditions:
                - condition: template
                  value_template: "{{ states(var_pump_mode) == 'Auto' }}"
                - condition: state
                  entity_id: !input pool_pump
                  state: 'on'
                - condition: template
                  value_template: '{{ var_pump_running_time >= var_cycle_runtime }}'
            sequence:
                - service: switch.turn_off
                  target:
                      entity_id: !input pool_pump
          # Auto cycle startup
          - conditions:
                - condition: template
                  value_template: "{{ states(var_pump_mode) == 'Auto' }}"
                - condition: state
                  entity_id: !input pool_pump
                  state: 'off'
                - condition: template
                  value_template: '{{ var_time_in_range }}'
                - condition: template
                  value_template: '{{ var_pump_state_changed_since > var_pump_interval }}'
                - condition: template
                  value_template: '{{ var_manual_runtime_today < var_calculated_daily_limit }}'
                - condition: template
                  value_template: '{{ var_manual_runtime_today < var_maximum_run_time }}'
            sequence:
                - service: switch.turn_on
                  target:
                      entity_id: !input pool_pump
      default: []

mode: single
